### ISSUE TITLE
How to make PR curve monotonically decreasing

### ISSUE THREAD

**Issue by arashash** [rafaelpadilla/review_object_detection_metrics#62] opened 2021-06-19 19:13 UTC
Hii, Thank you so much for this, saved me a ton of time!

I have an issue with the Pascal VOC implementation:
I was reading the Pascal VOC 2012 doc which defines AP like,

![image](https://user-images.githubusercontent.com/15813444/122653080-031e4580-d14b-11eb-8eb0-add5559ddfe2.png)

I was wondering why the outputs are not monotonically decreasing when I run this code?

![image](https://user-images.githubusercontent.com/15813444/122653142-758f2580-d14b-11eb-9a65-7bd4966cb4df.png)

**Comment by rafaelpadilla** [comment] 2021-07-21 21:03
Hi @arashash,

Thank you for your comment.

This behavior is not caused by the tool. Our tool produces the exact same results as the official PASCAL VOC 2012 development kit. This is a natural behavior caused by the metric itself, and you would see the same behavior in plots produced with the MATLAB tool. Such zig-zag shape may appear in many cases and is totally correct. 

The paper refers to the "computation" of the AP. Not the curve itself. The computation is not made on the plotted curve but in its interpolated monotonic version.

(I assume that you are aware of the computation of the Precision x Recall curve, so I won't review it here. In case you need a detailed explanation, I suggest taking a look at [this example](https://github.com/rafaelpadilla/Object-Detection-Metrics#an-ilustrated-example) and the example at section "5. A Numerical Example" in the paper.)

The curve is indeed zig-zagged, but the **computation** is made on the monotonic version of the curve, which is represented by the red dotted line in the plot below:

![image](https://user-images.githubusercontent.com/31217453/126559144-87ba80a4-e200-4db0-be00-0baa30b8617a.png)

I hope it answers your doubt.

Best regards,

**Comment by arashash** [comment] 2021-07-21 21:43
Woow thanks a million. This cleared up everything for me.

**Comment by rafaelpadilla** [comment] 2021-07-21 22:00
Glad to help, @arashash :)

I will close this issue. If you have further questions, you can reopen it or open a new one.

**Closed by rafaelpadilla** 2021-07-21 22:00 UTC
