### ISSUE TITLE
Program Crashing

### ISSUE THREAD

**Issue by zaradamou** [rafaelpadilla/review_object_detection_metrics#9] opened 2021-02-12 19:02 UTC
Hi!

I have labels and detections that I am using with YOLO. Once I load all of the annotations for groundtruth and detections to the GUI and click "Run", the program crashes. 

My issue might be related to the .txt files that I am using, this is an example of one of my .txt files for one of my images: 

Example from a .txt file in the groundtruth folder(generated from LabelImg tool): 
2 0.771250 0.220000 0.350000 0.335000 

Example from a .txt file in the detection folder(generated from darknet detector): 
1 0.2522 0.1515 0.2163 0.3143
0 0.6483 0.6727 0.8530 0.4814

I have a classes.txt file that I have also loaded 

This is the output from terminal: 

Traceback (most recent call last):
  File "/Users/zaraadamou/review_object_detection_metrics/src/ui/run_ui.py", line 312, in btn_run_clicked
    det_annotations, passed = self.load_annotations_det()
  File "/Users/zaraadamou/review_object_detection_metrics/src/ui/run_ui.py", line 154, in load_annotations_det
    ret = converter.text2bb(self.dir_dets,
  File "/Users/zaraadamou/review_object_detection_metrics/src/utils/converter.py", line 257, in text2bb
    if bb_type == BBType.DETECTED and not validations.is_relative_text_format(
  File "/Users/zaraadamou/review_object_detection_metrics/src/utils/validations.py", line 369, in is_relative_text_format
    if not is_empty_file(file_path):
  File "/Users/zaraadamou/review_object_detection_metrics/src/utils/validations.py", line 542, in is_empty_file
    for line in f:
  File "/Users/zaraadamou/opt/anaconda3/envs/objmetrics/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 99: invalid continuation byte
zsh: abort      python run.py

-Zara

**Comment by rafaelpadilla** [comment] 2021-02-12 20:20
Hi @zaradamou ,

Your detections have only 5 positions:
`1 0.2522 0.1515 0.2163 0.3143`

Note that the detection files must contain 6 blocks. I believe the confidence value is missing.

**Comment by zaradamou** [comment] 2021-02-12 21:12
Oh, I completely missed that! Thank you

**Comment by rafaelpadilla** [comment] 2021-02-12 21:24
@zaradamou,

You are welcome :)

If that solved your problem, please, close this issue

**Closed** 2021-02-13 19:35 UTC

**Comment by zaradamou** [comment] 2021-02-24 20:19
Hi Rafael, 

I updated the necessary information, and still receive the following error: 

File "/Users/zaraadamou/review_object_detection_metrics/src/ui/run_ui.py", line 312, in btn_run_clicked
    det_annotations, passed = self.load_annotations_det()
  File "/Users/zaraadamou/review_object_detection_metrics/src/ui/run_ui.py", line 154, in load_annotations_det
    ret = converter.text2bb(self.dir_dets,
  File "/Users/zaraadamou/review_object_detection_metrics/src/utils/converter.py", line 257, in text2bb
    if bb_type == BBType.DETECTED and not validations.is_relative_text_format(
  File "/Users/zaraadamou/review_object_detection_metrics/src/utils/validations.py", line 369, in is_relative_text_format
    if not is_empty_file(file_path):
  File "/Users/zaraadamou/review_object_detection_metrics/src/utils/validations.py", line 542, in is_empty_file
    for line in f:
  File "/Users/zaraadamou/opt/anaconda3/envs/objmetrics/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
zsh: abort      python run.py

I have attached my files to this message. 

Thank you! 

Best, 
Zara


[baggage_claim_gt.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6038624/baggage_claim_gt.txt)
[baggage_claim_dt.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6038627/baggage_claim_dt.txt)
![baggage_claim](https://user-images.githubusercontent.com/69253124/109060472-6fb09880-76b3-11eb-91a3-a7ded88b9f35.jpg)

[classes.txt](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6038634/classes.txt)

**Comment by rafaelpadilla** [comment] 2021-02-24 20:39
Hi @zaradamou, 

The name of the files you sent might be the cause of your problem. 

Given the image `baggage_claim.jpg`, both ground-truth and detection files of this image should be both named as 'baggage_claim.txt' and put in different folders. See the structure below:

![image](https://user-images.githubusercontent.com/31217453/109062425-af34b000-76c6-11eb-8ca5-c533b64b5fc3.png)

After that, choose the following options on the interface:

![image](https://user-images.githubusercontent.com/31217453/109062536-d3908c80-76c6-11eb-98fd-8f6f2c4c269e.png)

By that, you can obtain the following results:
![image](https://user-images.githubusercontent.com/31217453/109061913-05552380-76c6-11eb-80e6-5fc34619bd17.png)

![image](https://user-images.githubusercontent.com/31217453/109062024-27e73c80-76c6-11eb-9e5d-7b9d180469af.png)

I hope that helps.

Best regards,
Rafael

**Comment by zaradamou** [comment] 2021-02-25 16:27
Hi Rafael, 

Thank you for your very prompt responses. I have it saved in the format you have detailed and I still receive the same error unfortunately. 

Best, 
Zara

**Comment by rafaelpadilla** [comment] 2021-02-25 18:52
Hi Zara,

Have you replaced your code with the repo's last version?

I put your files in the attached file. Uncompress it in a folder and choose the options in the interface as in my previous message.
[samples_zaradamou.zip](https://github.com/rafaelpadilla/review_object_detection_metrics/files/6045134/samples_zaradamou.zip)

**Comment by zaradamou** [comment] 2021-02-25 22:25
Hi Rafael, 

Thank you so much, I replaced the code with the latest version and everything is running smoothly. This is a great program!

Best, 
Zara
