### ISSUE TITLE
UI interface issues in Windows 10 #help_needed

### ISSUE THREAD

**Issue by sheikhjubaer** [rafaelpadilla/review_object_detection_metrics#44] opened 2021-05-02 20:07 UTC
Hi @rafaelpadilla Sir,
Hope you are fine. Sir i would like to know you that i am using your project and i am facing trouble with the your projects UI interface in windows 10 (64 bit), as i am not not able to resize, close or minimize the UI interface; its freezing as it is appearing on my windows screen. And i am assuming some related warning showing up on command prompt which i tried to solve but failed. 
Here i am giving you some screenshot of my command prompt and windows screen. 
Hoping to hear you soon...
Thanks in advance!
# Command Prompt ::
![cmd](https://user-images.githubusercontent.com/65288399/116825966-7a0b7900-abb3-11eb-870d-c76fbf2818a5.jpg)
# Windows Screen ::
![win_interface](https://user-images.githubusercontent.com/65288399/116825969-7bd53c80-abb3-11eb-9b87-38ee753d86f1.jpg)

**Comment by rafaelpadilla** [comment] 2021-05-03 04:37
Hi @sheikhjubaer,

It looks like a problem with your QT lib. Was your `python1` environment created with [this](https://github.com/rafaelpadilla/review_object_detection_metrics/blob/main/environment.yml) .yml file?

Please, try to create an environment using the `environment.yml` file. Follow the instructions `[here](https://github.com/rafaelpadilla/review_object_detection_metrics#how-to-use-this-project)`.

**Comment by sheikhjubaer** [comment] 2021-05-03 06:53
Hi @rafaelpadilla sir,
Sir now i have done what you have instructed. But still the same problem! Though last time i had used my created environment in Anaconda.

**Comment by rafaelpadilla** [comment] 2021-05-03 07:06
Hi @sheikhjubaer,

In a quick google search, I noticed that some people have faced the same problem in other applications. They have overcome this problem changing values of some environment variables:

Take a look here: https://stackoverflow.com/questions/58194247/warning-qt-device-pixel-ratio-is-deprecated

Let me know if that works.

**Comment by sheikhjubaer** [comment] 2021-05-03 07:11
Sir @rafaelpadilla ,
I have already searched it in all sort of site available and tried to solve accordingly. But nothings seems working :(

**Comment by rafaelpadilla** [comment] 2021-05-03 07:20
@sheikhjubaer,

Unfortunately I cannot reproduce this error in my machine. Do you have pyqt / QT installed in your machine? What version?

I would also try to install pyqt and run `pyuic` to convert the .ui files to .py locally.

**Comment by rafaelpadilla** [comment] 2021-09-29 06:28
Closing issue as no update was reported

**Closed by rafaelpadilla** 2021-09-29 06:28 UTC
Labels: help wanted
